-- ============================================================
-- MERMS: Test User Seeds
-- Run in Supabase SQL editor AFTER running institution_registrations.sql
-- These create pre-verified accounts you can log in with immediately.
-- ============================================================

-- NOTE: Supabase auth users must be created via the Auth API or Dashboard.
-- Use these credentials in the Supabase Auth → Users → "Add User" panel,
-- OR run the insert below IF using the service role key directly.

-- ─── Test User Credentials (save these) ─────────────────────────────────────
--
--  INSTITUTION
--    Email:    institution@merms.test
--    Password: MermsInst@2026
--    Role:     institution
--
--  PHO
--    Email:    pho@merms.test
--    Password: MermsPHO@2026
--    Role:     pho
--    Clearance: regional_admin
--
--  EOC ADMIN
--    Email:    eoc@merms.test
--    Password: MermsEOC@2026
--    Role:     eoc
--
--  CIVILIAN
--    Email:    civilian@merms.test
--    Password: MermsCiv@2026
--    Role:     civilian
--
-- ─────────────────────────────────────────────────────────────────────────────

-- Seed the profiles table (run after creating users via Supabase Auth Dashboard)
-- Replace the UUIDs below with the actual UUIDs generated by Supabase Auth.

-- Example profile inserts — update UUIDs after creating auth users:
/*
INSERT INTO public.profiles (id, email, role, first_name, last_name) VALUES
  ('00000000-0000-0000-0000-000000000001', 'institution@merms.test', 'institution', 'Test', 'Institution'),
  ('00000000-0000-0000-0000-000000000002', 'pho@merms.test',         'pho',         'Test', 'PHO'),
  ('00000000-0000-0000-0000-000000000003', 'eoc@merms.test',         'eoc',         'Test', 'EOC'),
  ('00000000-0000-0000-0000-000000000004', 'civilian@merms.test',    'civilian',    'Test', 'Civilian')
ON CONFLICT (id) DO NOTHING;
*/

-- ─── Quick setup via MERMS Register API ────────────────────────────────────
-- Alternatively, just curl the /auth/register endpoint:
--
-- curl -X POST http://localhost:3000/auth/register \
--   -H "Content-Type: application/json" \
--   -d '{"email":"pho@merms.test","password":"MermsPHO@2026","role":"pho","firstName":"Test","lastName":"PHO"}'
--
-- curl -X POST http://localhost:3000/auth/register \
--   -H "Content-Type: application/json" \
--   -d '{"email":"eoc@merms.test","password":"MermsEOC@2026","role":"eoc","firstName":"Test","lastName":"EOC"}'
--
-- curl -X POST http://localhost:3000/auth/register \
--   -H "Content-Type: application/json" \
--   -d '{"email":"civilian@merms.test","password":"MermsCiv@2026","role":"civilian","firstName":"Test","lastName":"Civilian"}'
